{% set name = "objgraph" %}
{% set version = "3.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe96c74147bbcaae8665b396e5388bdcc3197deebba4e6381f05202ee5b453a7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python-graphviz
    - python

test:
  requires:
    - pip
  imports:
    - objgraph
  commands:
    - python -m pip check

about:
  home: https://pypi.org/project/objgraph
  summary: Draws Python object reference graphs with graphviz
  license: MIT
  license_file: LICENSE
  doc_url: https://mg.pov.lt/objgraph
  dev_url: https://github.com/mgedmin/objgraph

extra:
  recipe-maintainers:
    - marcelotrevisani
